language: python
sudo: false
python:
    - "3.4"
    - "3.5"
install:
    - pip install -qU pip wheel
    - pip install -q -U -r requirements.txt
script:
    - flake8 cockatiel functional_tests
    - py.test functional_tests
cache:
    directories:
        - $HOME/.cache/pip